<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.dows.cloud</groupId>
        <artifactId>dows-uim</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>uim-feign</artifactId>


    <dependencies>
        <!--<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
        </dependency>-->
        <dependency>
            <groupId>org.dows.cloud</groupId>
            <artifactId>uim-api</artifactId>
        </dependency>
    </dependencies>
</project>
