<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <!--<parent>
        <artifactId>dows-parent</artifactId>
        <groupId>org.dows.framework</groupId>
        <version>20240120-SNAPSHOT</version>
    </parent>-->

    <parent>
        <groupId>org.dows.framework</groupId>
        <artifactId>rade-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>dows-uim</artifactId>
    <groupId>org.dows.cloud</groupId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <properties>
        <revision>1.0.0-SNAPSHOT</revision>
        <dows-hrm.version>1.0.0-SNAPSHOT</dows-hrm.version>
        <mybatis-flex.ext.version>1.10.8.110</mybatis-flex.ext.version>
        <jdk.version>23</jdk.version>
        <!--<spring-cloud-dependencies.version>2024.0.0</spring-cloud-dependencies.version>-->
        <!--<springdoc-openapi.version>2.6.0</springdoc-openapi.version>-->
        <!--<swagger.version>2.2.28</swagger.version>-->
<!--
        <springdoc-openapi.version>2.8.6</springdoc-openapi.version>
        <swagger.version>2.2.28</swagger.version>-->
    </properties>


    <modules>
        <module>uim-api</module>
        <module>uim-app</module>
        <module>uim-biz</module>
        <module>uim-boot</module>
        <module>uim-cache</module>
        <module>uim-config</module>
        <module>uim-handler</module>
        <module>uim-service</module>
        <module>uim-rest</module>
        <module>uim-pojo</module>
        <module>uim-feign</module>
    </modules>

    <dependencyManagement>
        <dependencies>

            <dependency>
                <artifactId>uim-api</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <artifactId>uim-app</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <artifactId>uim-biz</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <artifactId>uim-boot</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <artifactId>uim-cache</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <artifactId>uim-config</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <artifactId>uim-feign</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <artifactId>uim-handler</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <artifactId>uim-pojo</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${project.version}</version>
            </dependency>

            <!-- <dependency>
                 <artifactId>uim-entity</artifactId>
                 <groupId>org.dows.cloud</groupId>
                 <version>${project.version}</version>
             </dependency>
             <dependency>
                 <artifactId>uim-mapper</artifactId>
                 <groupId>org.dows.cloud</groupId>
                 <version>${project.version}</version>
             </dependency>-->
            <dependency>
                <artifactId>uim-service</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${project.version}</version>
            </dependency>


            <dependency>
                <artifactId>uim-rest</artifactId>
                <groupId>org.dows.cloud</groupId>
                <version>${project.version}</version>
            </dependency>


<!--            <dependency>-->
<!--                <groupId>org.dows.cloud</groupId>-->
<!--                <artifactId>hrm-feign</artifactId>-->
<!--                <version>${dows-hrm.version}</version>-->
<!--            </dependency>-->

            <dependency>
                <groupId>org.aspectj</groupId>
                <artifactId>aspectjweaver</artifactId>
                <version>${aspectj.version}</version>
            </dependency>

<!--            <dependency>-->
<!--                <groupId>com.tangzc</groupId>-->
<!--                <artifactId>mybatis-flex-ext-spring-boot3-starter</artifactId>-->
<!--                <version>${mybatis-flex.ext.version}</version>-->
<!--            </dependency>-->
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <distributionManagement>
        <repository>
            <id>2290151-snapshot-aLhHBl</id>
            <url>https://packages.aliyun.com/634f4de0327f73640e96c28d/maven/2290151-snapshot-alhhbl</url>
        </repository>
        <snapshotRepository>
            <id>2290151-snapshot-aLhHBl</id>
            <url>https://packages.aliyun.com/634f4de0327f73640e96c28d/maven/2290151-snapshot-alhhbl</url>
        </snapshotRepository>
    </distributionManagement>

</project>
