sonar.projectKey=rade_rade-uim_45c67c5d-87f0-45d3-ac2f-0bf3852a3cf1
sonar.projectName=reade-uim
#sonar.projectVersion=1.0.240218
sonar.language=java
sonar.java.source=23
sonar.java.binaries=.
sonar.sources=.
sonar.host.url=http://192.168.111.103:9001
sonar.login=admin
sonar.password=rade123!
#sonar.qualitygate.wait=true




