spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    #    schema: classpath:form-schema.sql
    #    data: classpath:form-data.sql
    hikari:
      # 连接池允许的最大连接数
      maximum-pool-size: 100
      # 连接池保持的最小空闲连接数
      minimum-idle: 50
      # 获取连接的最大等待时间（毫秒）
      connectionTimeout: 60000
      # 连接在空闲状态下的最大存活时间（毫秒）
      idleTimeout: 300000
      # 连接的最大存活时间（毫秒）
      maxLifetime: 1800000
      # 是否自动提交事务
      autoCommit: true
      # 用于测试连接是否有效的 SQL 查询语句
      connectionTestQuery: SELECT 1
      # 连接池的名称，用于日志和监控
      poolName: UimHikariCP



---
#开发环境
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://115.159.24.40:13306/dev_bole?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: encrypted$HnOB7XSpPC5NvdV5HYhzAQ==
    password: encrypted$jwBBPVuexU/i22za5nVxCg==

    #driver-class-name: com.mysql.cj.jdbc.Driver
---
#开发环境
spring:
  config:
    activate:
      on-profile: sit

  datasource:
    url: jdbc:mysql://115.159.24.40:13306/bole?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: encrypted$HnOB7XSpPC5NvdV5HYhzAQ==
    password: encrypted$jwBBPVuexU/i22za5nVxCg==
---
#开发环境
spring:
  config:
    activate:
      on-profile: prd

  datasource:
    url: jdbc:mysql://192.168.111.103:3306/rade?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: rade
    password: rade123!

