dows:
  cdc:
    jobs:
      - handle-class: org.dows.task.cdc.MssqlMessageHandler
        enable: true
        datasource-name: acre-mssql
        dbType: mssql
        descr: 描述
        properties:
          "connector.class": "io.debezium.connector.sqlserver.SqlServerConnector"
          "name": "MSSQL_ORDER"
          "database.hostname": "192.168.111.103"
          "database.port": "11433"
          "database.user": "sa"
          "database.password": "shdy123!"
          "database.names": "acre"
          "database.encrypt": "false"
#          "database.ssl.truststore": "path/to/trust-store",
#          "database.ssl.truststore.password": "password-for-trust-store"
          "topic.prefix": "work-order"
#          "table.include.list": "dbo.customers",
          "offset.storage.file.filename": "mssql-offset.dat"
          "offset.flush.interval.ms": "3000"
#          "schema.history.internal.kafka.bootstrap.servers": "kafka:9092",
#          "schema.history.internal.kafka.topic": "schemahistory.fullfillment",

        history-file: mssql-history.dat
        tables:
          - dbo.work_order
          - dbo.agent_control
          - dbo.eqpt_coord
          - dbo.AllZone_ScanValue

      - name: MYSQL_LOG
        datasource-name: acre-mysql
        enable: false
        descr: 描述
        dbType: mysql
        topicPrefix: mysql-log
        serverId: 4
        offsetInterval: 3000
        offset-file: mysql-offset.dat
        history-file: mysql-history.dat
        connector-class: io.debezium.connector.mysql.MySqlConnector
        handle-class: org.dows.log.handler.LogSinkHandler
        databases:
          - wes_all
        tables:
          - wes_all.log_column
