spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    #    schema: classpath:form-schema.sql
    #    data: classpath:form-data.sql
    hikari:
      maximum-pool-size: 100
      minimum-idle: 50
      connectionTimeout: 6000



---
#开发环境
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://127.0.0.1:13306/rade?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: rade
    password: 123456
    #driver-class-name: com.mysql.cj.jdbc.Driver

---
#开发环境
spring:
  config:
    activate:
      on-profile: prd

  datasource:
    url: jdbc:mysql://192.168.111.103:3306/rade?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: rade
    password: rade123!

